const PDFDocument = require("pdfkit");
const { json } = require("./_lib/response");
const { getCV, getDefaultPublishedCV } = require("./_lib/repository");
const { requireAdmin } = require("./_lib/auth");

function themeColors(theme) {
  if (theme === "neon_grid") return { primary: "#0fd3ff", text: "#08101a", muted: "#3f4d63", bg: "#f4fbff" };
  if (theme === "atelier") return { primary: "#e25d3e", text: "#1e1b18", muted: "#6a625a", bg: "#fff9f4" };
  return { primary: "#1d3557", text: "#17202c", muted: "#4a5666", bg: "#f8fafc" };
}

function addHeading(doc, text, colors) {
  doc.fillColor(colors.primary).font("Helvetica-Bold").fontSize(14).text(text.toUpperCase(), { underline: false });
  doc.moveDown(0.3);
  doc.strokeColor(colors.primary).lineWidth(1).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.5);
}

function blockText(block) {
  const content = block.content || {};
  switch (block.type) {
    case "summary":
      return String(content.text || "");
    case "experience_short":
      return `${content.role || ""} - ${content.company || ""} (${content.period || ""})\n${content.impact || ""}`;
    case "experience_detailed":
      return `${content.role || ""} - ${content.company || ""} (${content.period || ""})\n${content.details || ""}`;
    case "diploma":
      return `${content.degree || ""} - ${content.school || ""} (${content.year || ""})`;
    case "certification":
      return `${content.name || ""} - ${content.org || ""} (${content.year || ""})`;
    case "skills":
      return Array.isArray(content.items) ? content.items.join(", ") : String(content.text || "");
    case "tools":
      return Array.isArray(content.items) ? content.items.join(", ") : String(content.text || "");
    default:
      return JSON.stringify(content);
  }
}

function safeFilename(name) {
  return String(name || "CV").replace(/[^a-zA-Z0-9_-]+/g, "_").slice(0, 80);
}

async function readCv(event) {
  const id = event.queryStringParameters && event.queryStringParameters.id;
  if (id) {
    const auth = requireAdmin(event);
    if (!auth.ok) return { error: auth.response };
    const cv = await getCV(event, id);
    if (!cv) return { error: json(404, { ok: false, error: "CV introuvable" }) };
    return { cv };
  }

  const cv = await getDefaultPublishedCV(event);
  if (!cv) return { error: json(404, { ok: false, error: "Aucun CV publie" }) };
  return { cv };
}

exports.handler = async function handler(event) {
  if (event.httpMethod !== "GET") return json(405, { ok: false, error: "Method not allowed" });

  const result = await readCv(event);
  if (result.error) return result.error;
  const cv = result.cv;
  const colors = themeColors(cv.theme);

  const doc = new PDFDocument({ size: "A4", margin: 50 });
  const chunks = [];
  doc.on("data", (chunk) => chunks.push(chunk));

  doc.rect(0, 0, doc.page.width, doc.page.height).fill(colors.bg);
  doc.fillColor(colors.text).font("Helvetica-Bold").fontSize(28).text(cv.fullName || cv.title, 50, 52);
  doc.fillColor(colors.muted).font("Helvetica").fontSize(12).text(cv.role || "", 50, 92);
  doc.moveDown(1.8);

  if (cv.summary) {
    addHeading(doc, "Resume professionnel", colors);
    doc.fillColor(colors.text).font("Helvetica").fontSize(11.5).text(cv.summary, { lineGap: 3 });
    doc.moveDown(0.8);
  }

  if (cv.blocks && cv.blocks.length) {
    addHeading(doc, "Sections", colors);
    cv.blocks
      .filter((b) => b.enabled !== false)
      .sort((a, b) => (a.order || 0) - (b.order || 0))
      .forEach((block) => {
        doc.fillColor(colors.primary).font("Helvetica-Bold").fontSize(11.2).text(block.title || block.type);
        doc.fillColor(colors.text).font("Helvetica").fontSize(10.5).text(blockText(block), { lineGap: 2 });
        doc.moveDown(0.7);
      });
  }

  const footerY = doc.page.height - 40;
  doc.fillColor(colors.muted).font("Helvetica-Oblique").fontSize(9).text("Generated by CV Manager", 50, footerY);
  doc.end();

  const buffer = await new Promise((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });

  const fileName = `CV_${safeFilename(cv.fullName || cv.title)}.pdf`;
  return {
    statusCode: 200,
    isBase64Encoded: true,
    headers: {
      "content-type": "application/pdf",
      "content-disposition": `attachment; filename=\"${fileName}\"`,
      "cache-control": "no-store"
    },
    body: buffer.toString("base64")
  };
};
